server:
  port: 8080
  servlet:
    context-path: /builtrix

spring:
  profiles:
    include:
      - aws
  mvc:
    locale: en_US

metrics:
  token:
    email:
      length: 48
      expiration: 300
