server:
  port: 8080
  servlet:
    context-path: /builtrix

spring:
  profiles:
    active: dev
    include:
      - aws
  mvc:
    locale: en_US

metrics:
  token:
    email:
      length: 48
      expiration: 300

  email:
    template-path: classpath:templates.email
    aws:
      server:
      userName:
      password:
      port: 9090
      default-account:
