server:
  port: 8080
  servlet:
    context-path: /builtrix
  address:

spring:
  profiles:
    active: dev
    include:
      - aws
  mvc:
    locale: en_US
  servlet:
    multipart:
      max-file-size: 12MB

metrics:
  token:
    email:
      length: 48
      expiration: 300

  email:
    url: "http://${server.address}:${server.port}/v1/auth/emailConfirmation"
    template-path: classpath:templates.email
    aws:
      server: email-smtp.us-east-1.amazonaws.com
      userName: AKIA3JX2C3UJMAETIRKP
      password: BL8aNm+rflWqVg2sypbb3W824SfWMXW4mFjDGe2ouzxi
      port: 587
      default-account: info@builtrix.tech
      from: info@builtrix.tech
  redirect:
    #    url: "http://localhost:4200/login?returnUrl=%2F"
    url: http://metric-clients-virginia.s3-website-us-east-1.amazonaws.com

  report:
    reportPath:
