package tech.builtrix.models.building.enums;

public enum BuildingUsage {
	OFFICE_BUILDING_OR_CO_WORK_SPACE,
	HOTEL_OR_SIMILAR_BUILDINGS,
	HOSPITAL_OR_SIMILAR_BUILDINGS,
	FITNESS_CENTER_OR_SIMILAR_BUILDINGS,
	UNIVERSITY_OR_SIMILAR_BUILDINGS,
	SUPERMARKET,
	SHOPPING_CENTER,
	MULTI_PURPOSE_BUILDING,
	UNKNOWN
}
